# Variables path
path_save: '../../../data/forecast-results/model/long-term0/regressor/'

# Data files
observation_data_path: ['/home/toqflo/data/data-set/valid_metro_15min_2015_2016_2017_sumpass_nodayfree.csv']
features_data_path: ['/home/toqflo/data/data-set/events_2015_2018_end_event_stopid.csv',
                     '/home/toqflo/data/data-set/events_2015_2018_start_event_stopid.csv',
                     '/home/toqflo/data/data-set/events_2015_2018_period_event_stopid.csv',
                     '/home/toqflo/data/data-set/events_2015_2018_end_event_stopid_category.csv',
                     '/home/toqflo/data/data-set/events_2015_2018_start_event_stopid_category.csv',
                     '/home/toqflo/data/data-set/events_2015_2018_period_event_stopid_category.csv',
                     '/home/toqflo/data/data-set/predicted_weather_2015_2017_included_perday_pm.csv',
                     '/home/toqflo/data/data-set/2013-01-01-2019-01-01_new.csv',
                     '/home/toqflo/data/data-set/trend_r_stl_2015-01-01_2018-01-01_freq30.csv']

