# Variables path
path_save: '/home/toque/data2/forecast/model/long-term/scikit-regressor/'

# Data files
observation_data_path: ['/home/toque/data2/montreal/stm/data/valid_metro_15min_2015_2016_2017_sumpass_nodayfree.csv']
features_data_path: ['/home/toque/data2/montreal/events/data/clean/events_2015_2018_end_event_stopid.csv',
                     '/home/toque/data2/montreal/events/data/clean/events_2015_2018_start_event_stopid.csv',
                     '/home/toque/data2/montreal/events/data/clean/events_2015_2018_period_event_stopid.csv',
                     '/home/toque/data2/montreal/events/data/clean/events_2015_2018_end_event_stopid_category.csv',
                     '/home/toque/data2/montreal/events/data/clean/events_2015_2018_start_event_stopid_category.csv',
                     '/home/toque/data2/montreal/events/data/clean/events_2015_2018_period_event_stopid_category.csv',
                     '/home/toque/data2/weather/predicted_weather/predicted_weather_2015_2017_included_perday_pm.csv',
                     '/home/toque/data2/date/2013-01-01-2019-01-01_new.csv',
                     '/home/toque/data2/montreal/stm/data/trend/trend_r_stl_2015-01-01_2018-01-01_freq30.csv']
