# Configuration of the learning step of the Random Forest model


#start_date_train: string date, format 'YYYY-MM-dd hh:mm:ss',
#end_date_train: string date, format 'YYYY-MM-dd hh:mm:ss',
#start_date_test: string date, format 'YYYY-MM-dd hh:mm:ss',
#end_date_test: string date, format 'YYYY-MM-dd hh:mm:ss',
#file_path_obs: list of string file path of observation
#file_path_pred: list of string file path of prediction
#list_name_pred: list of string name of the prediction model
#time_series: list string id of the time series
#time_series_name: list of string of the time series name could be Null
#directory_path_to_save: string directory path to save the evaluation files
#name_evaluation: string name of the evaluation

AT: 5
start_date_train: '2015'
end_date_train: '2017'
start_date_test: '2017'
end_date_test: '2018'
file_path_obs: ['/home/toque/data2/montreal/stm/data/valid_metro_15min_2015_2016_2017_sumpass_nodayfree.csv']
#file_path_pred: ["/home/toque/data2/forecast/model/ha/prediction/lt_ha_mtl_v1/2015-01-01_2017-12-31_mean.csv",
#                 "/home/toque/data2/forecast/model/ha/prediction/lt_ha_mtl_v2/2015-01-01_2017-12-31_mean.csv",
#                 "/home/toque/data2/forecast/model/ha/prediction/lt_ha_mtl_v3/2015-01-01_2017-12-31_mean.csv",
#                 "/home/toque/data2/forecast/model/rf/prediction/lt_rf_mtl/2015-01-01_2017-12-31.csv",
#                 "/home/toque/data2/forecast/model/rf/prediction/lt_rf_mtl_weather_gcca_daily/2015-01-01_2017-12-31.csv",
#                 "/home/toque/data2/forecast/model/rf/prediction/lt_rf_mtl_weather_gcca_per_hour/2015-01-01_2017-12-31.csv"]
#file_path_pred: [ "/home/toque/data2/forecast/model/ha/prediction/lt_ha_mtl_dropnaexogenousweather/2015-01-01_2017-12-31_mean.csv",
#                  "/home/toque/data2/forecast/model/rf/prediction/lt_rf_mtl_dropnaexogenousweather/2015-01-01_2017-12-31.csv",
#                  "/home/toque/data2/forecast/model/rf/prediction/mt_rf_mtl_predweatherdaypm_dropnaexogenousweather/2015-01-01_2017-12-31.csv",
#                  "/home/toque/data2/forecast/model/rf/prediction/mt_rf_mtl_predweatherhour_dropnaexogenousweather/2015-01-01_2017-12-31.csv",
#                  "/home/toque/data2/forecast/model/rf/prediction/mt_rf_mtl_events/2015-01-01_2017-12-31.csv",
#                  "/home/toque/data2/forecast/model/rf/prediction/mt_rf_mtl_events_multi_10stops/2015-01-01_2017-12-31.csv",
#                  "/home/toque/data2/forecast/model/rf_inverted/prediction/rf_inverted_15stationsexo_contextcal_withoutoptim6min/2015-01-01_2016-12-31.csv",
#                  "/home/toque/data2/forecast/model/rf_inverted/prediction/rf_inverted_10stationsexo_contextcal_withoutoptim6min/2015-01-01_2016-12-31.csv",
#                  "/home/toque/data2/forecast/model/rf_inverted/prediction/rf_inverted_0stationsexo_contextcal_withoutoptim6min/2015-01-01_2016-12-31.csv",
#                  "/home/toque/data2/forecast/model/rf_inverted/prediction/rf_inverted_0stationsexo_contextcalmeteoday_withoutoptim6min/2015-01-01_2016-12-31.csv",
#                  "/home/toque/data2/forecast/model/rf_inverted/prediction/rf_inverted_15stationsexo_contextcalmeteoday_withoutoptim6min/2015-01-01_2016-12-31.csv",
#                  "/home/toque/data2/forecast/model/rf_uni/prediction/rf_uni_event_15stations_optim1timeseries/2015-01-01_2017-12-31.csv"
#                  ]
file_path_pred: [ "/home/toque/data2/forecast/model/ha/prediction/lt_ha_mtl/2015-01-01_2017-12-31_mean.csv",
                  "/home/toque/data2/forecast/model/rf_uni_inverted/prediction/lt_rf_uni_inverted/2015-01-01_2017-12-31.csv",
                  "/home/toque/data2/forecast/model/rf_uni_inverted/prediction/mt_rf_uni_inverted_events15/2015-01-01_2017-12-31.csv",
                  "/home/toque/data2/forecast/model/rf_uni_inverted/prediction/mt_rf_uni_inverted_events15_detrended_lt_rf_uni_inverted/2015-01-01_2017-12-31.csv",
                  "/home/toque/data2/forecast/model/rf_st_InMulti_OutUni/prediction/st_rf_InMulti_OutUni/2015-01-01_2017-12-31.csv",
                  "/home/toque/data2/forecast/model/rf_st_InUni_OutUni/prediction/st_rf_InUni_OutUni/2015-01-01_2017-12-31.csv"
                  ]

#list_name_pred: ['lt_ha_v1', 'lt_ha_v2', 'lt_ha_v3', 'lt_rf', 'mt_rf_weather_gcca_daily','mt_rf_weather_gcca_per_hour']
#list_name_pred: [ 'lt_ha_dropnaexogenousweather', 'lt_rf_mtl',
#                  'mt_rf_mtl_predweatherdaypm',
#                  'mt_rf_mtl_predweatherhour',
#                  'mt_rf_mtl_events_multi_15stops',
#                  'mt_rf_mtl_events_multi_10stops','rf_inverted_withoutOptim_15stations',
#                  'rf_inverted_withoutOptim_10stations','rf_inverted_withoutOptim_0stations',
#                  'rf_inverted_withoutOptim_0stations_meteo', 'rf_inverted_withoutOptim_15stations_meteo',
#                  'rf_uni_event15_optim1timeseries']
list_name_pred: [ 'lt_ha_mtl',
                  'lt_rf_uni_inverted',
                  'mt_rf_uni_inverted_events15',
                  'mt_rf_uni_inverted_events15_detrended',
                  'st_rf_InMultiOutUni',
                  'st_rf_InUniOutUni',
                  ]
time_series: ['11', '32', '34', '15', '44', '65', '31', '33', '35', '47', '13', '14', '1', '9', '5', '18',
               '36', '24', '68', '43', '8', '64', '10', '55', '3', '49', '51', '2', '19', '56', '7', '6',
               '4', '48', '66', '25', '23', '28', '39', '54', '60', '27', '20', '46', '12', '21', '62', '52',
               '41', '50', '30', '16', '37', '40', '26', '67', '57', '61', '42', '45', '38', '29', '58',
               '63', '22', '59', '53', '17']
time_series_name: ['Berri-UQAM', 'McGill', 'Guy-Concordia', 'Bonaventure',
                   'Longueuil', 'Cote-Vertu', 'Place-des-Arts',
                   'Peel', 'Atwater', 'Vendome', "Place-d'Armes",
                   'Square-Victoria', 'Henri-Bourassa', 'Mont-Royal',
                   'Jean-Talon', 'Honore-Beaugrand', 'Lionel-Groulx', 'Pie-IX',
                   'Montmorency', 'Angrignon', 'Laurier', 'Saint-Michel',
                   'Sherbrooke', 'Cote-des-Neiges', 'Cremazie', 'Snowdon',
                   'Plamondon', 'Sauve', 'Radisson', 'Univ-de-Montreal',
                   'Rosemont', 'Beaubien', 'Jarry', 'Villa-Maria', 'Cartier',
                   'Joliette', 'Viau', 'Papineau', "De l'eglise", 'Du College',
                   'Parc', 'Frontenac', 'Langelier', 'Place-St-Henri',
                   'Champ-de-Mars', 'Station Cadillac', 'Station Fabre', 'Namur', 'Jolicoeur',
                   'Cote-Ste-Catherine', 'Saint-Laurent', "Lucien-L'Allier",
                   'Charlevoix', 'Verdun', 'Prefontaine', 'De la Concorde',
                   'edouard-Montpetit', 'De Castelnau', 'Station Monk', 'Jean-Drapeau',
                   'LaSalle', 'Beaudry', 'Outremont', "D'Iberville",
                   'Assomption', 'Acadie', 'De la Savane', 'Georges-Vanier']
#time_series_name:
directory_path_to_save:  '/home/toque/data2/forecast/evaluation/'
name_evaluation: 'eval_forecast_mtl_metro'

