# Configuration of the learning step of the Random Forest model


# observation_data_path: csv file path with the observation (header: 'Datetime', 'time_series_id1','time_series_id2', ...)
# exogenous_data_path: csv file path with the exogenous data (header: 'Datetime', 'feature_id1','feature_id2', ...)
# features: selected features of exogenous file
# time_series: selected time-series to learn of observation file
# model_name: name of the model (e.g. 'my_new_model')
# path_to_save: path of the directory in which the model will be saved
# start_date: format 'YYYY-MM-dd hh:mm:ss', starting date of the learning dataset
# end_date: format 'YYYY-MM-dd hh:mm:ss', ending date of the learning dataset



# Obligated not None
path_to_save: '/home/toque/data2/forecast/model/rf/fit/'




# WARNING : Everything None in A and nothing None in B or nothing None in A and everything None in B

# A)
path_grid_search_dict: '/home/toque/data2/forecast/model/rf/optimize/mt_rf_mtl_events2/grid_search_dict.pkl'
model_path: '/home/toque/data2/forecast/model/rf/optimize/mt_rf_mtl_events2/mt_rf_mtl_events2.pkl'

# B)
observation_data_path:
exogenous_data_path:
features_list:
time_series:
model_name:
start_date:
end_date:
scaler_choice:
best_params:
features:




