# Configuration of the optimization of the rf model


# observation_data_path: csv file path with the observation (header: 'Datetime', 'time_series_id1','time_series_id2', ...)
# exogenous_data_path: csv file path with the exogenous data (header: 'Datetime', 'feature_id1','feature_id2', ...)
# features: selected features of exogenous file
# time_series: selected time-series to learn of observation file
# model_name: name of the model (e.g. 'my_new_model')
# path_to_save: path of the directory in which the model will be saved
# start_date: format 'YYYY-MM-dd hh:mm:ss', starting date of the learning dataset
# end_date: format 'YYYY-MM-dd hh:mm:ss', ending date of the learning dataset
# param_kfold:
# param_grid:
# scoring:
# scaler_choice: "minmax" or "standard"



# Example
#observation_data_path: ['/home/toque/data2/montreal/stm/data/valid_metro_15min_2015_2016_2017_sumpass.csv']
#exogenous_data_path: ['/home/toque/data2/date/2013-01-01-2019-01-01_new.csv']
#features_list : [["Day_id", "Mois_id", "hms_int_15min", "24DEC", "31DEC", "day_off_quebec", "vac_noel_quebec"], ]
#                 ["Day_id","Mois_id","hms_int_15min","24DEC","Ferie","Pont","Vacances"],
#                 ["Day_id","Mois_id","hms_int_15min","Ferie","Pont","Vacances"],
#                 ["Day_id","hms_int_15min","Ferie","Pont","Vacances"]]
#time_series: ['11', '32', '34', '15', '44', '65', '31', '33', '35', '47', '13', '14',
#              '1', '9', '5', '18', '36', '24', '68', '43', '8', '64', '10', '55', '3',
#              '49', '51', '2', '19', '56', '7', '6', '4', '48', '66', '25', '23', '28',
#              '39', '54', '60', '27', '20', '46', '12', '21', '62', '52', '41', '50', '30',
#              '16', '37', '40', '26', '67', '57', '61', '42', '45', '38', '29', '58', '63',
#              '22', '59', '53', '17']
#model_name: rf_lt_example
#path_to_save: '/home/toque/data2/forecast/model/rf/optimize/'
#start_date: '2015-01-01 00:00:00'
#end_date: '2016-12-31 23:45:00'
#param_kfold:
#    n_splits: 5
#    shuffle: True
#    random_state: 0
#param_grid:
#    n_estimators: [100, 150, 200]
#    max_features: ['auto','sqrt']
#    max_depth: [null]
#    min_samples_leaf: [1,5,10]
#    min_samples_split: [2, 5, 10]
#    n_jobs: [6]
#    criterion: ['mse']
#scoring: "neg_mean_squared_error"
#scaler_choice : minmax


observation_data_path: ['/home/toque/data2/montreal/stm/data/valid_metro_15min_2015_2016_2017_sumpass_nodayfree.csv']
exogenous_data_path: ['/home/toque/data2/date/2013-01-01-2019-01-01_new.csv',
                      '/home/toque/data2/weather/predicted_weather/predicted_weather_2015_2017_included_perday_am.csv',
                      '/home/toque/data2/weather/predicted_weather/predicted_weather_2015_2017_included_perday_pm.csv',
                      '/home/toque/data2/weather/predicted_weather/predicted_weather_2015_2017_included_perhour.csv',
                      '/home/toque/data2/montreal/events/data/clean/events_2015_2018_start_event_stopid.csv',
                      '/home/toque/data2/montreal/events/data/clean/events_2015_2018_end_event_stopid.csv',
                      '/home/toque/data2/montreal/events/data/clean/events_2015_2018_period_event_stopid.csv']
features_list: [['hms_int_15min','Day_id', 'Mois_id','vac_noel_quebec', 'day_off_quebec', '24DEC', '31DEC',
                 'renov_beaubien', 'vac_udem1', 'vac_udem2','5-start_event', '11-start_event', '12-start_event',
                 '13-start_event', '15-start_event', '16-start_event',
                 '23-start_event', '24-start_event', '31-start_event',
                 '32-start_event', '35-start_event', '43-start_event',
                 '45-start_event', '61-start_event', '68-start_event', '5-end_event',
                 '11-end_event', '12-end_event', '13-end_event', '15-end_event',
                 '16-end_event', '23-end_event', '24-end_event', '31-end_event',
                 '32-end_event', '35-end_event', '43-end_event', '45-end_event',
                 '61-end_event', '68-end_event', '5-period_event', '11-period_event',
                 '12-period_event', '13-period_event', '15-period_event',
                 '16-period_event', '23-period_event', '24-period_event',
                 '31-period_event', '32-period_event', '35-period_event',
                 '43-period_event', '45-period_event', '61-period_event',
                 '68-period_event' ]]
time_series: ['11', '32', '34', '15', '44', '65', '31', '33', '35', '47', '13', '14',
              '1', '9', '5', '18', '36', '24', '68', '43', '8', '64', '10', '55', '3',
              '49', '51', '2', '19', '56', '7', '6', '4', '48', '66', '25', '23', '28',
              '39', '54', '60', '27', '20', '46', '12', '21', '62', '52', '41', '50', '30',
              '16', '37', '40', '26', '67', '57', '61', '42', '45', '38', '29', '58', '63',
              '22', '59', '53', '17']
model_name: mt_rf_mtl_events2
path_to_save: '/home/toque/data2/forecast/model/rf/optimize/'
start_date: '2015-01-01 00:00:00'
end_date: '2016-12-31 23:45:00'
param_kfold:
    n_splits: 5
    shuffle: True
    random_state: 0
param_grid:
    n_estimators: [300,400]
    max_features: ['auto',null]
    max_depth: [null]
    min_samples_split: [2,5,10]
    min_samples_leaf: [1,5,10]
    n_jobs: [6]
    criterion: ['mse']
scoring: "neg_mean_squared_error"
scaler_choice: "standard"

#'hms_int_15min',
