features_time_step: []

features_day: ['Day_en', 'Mois']

features_todummy: ['Day_en', 'Mois']

time_series: ['11', '32', '34', '15', '44', '65', '31', '33', '35', '47', '13',
       '14', '1', '9', '5', '18', '36', '24', '68', '43', '8', '64', '10',
       '55', '3', '49', '51', '2', '19', '56', '7', '6', '4', '48', '66',
       '25', '23', '28', '39', '54', '60', '27', '20', '46', '12', '21',
       '62', '52', '41', '50', '30', '16', '37', '40', '26', '67', '57',
       '61', '42', '45', '38', '29', '58', '63', '22', '59', '53', '17']


start_datetime: '2015-01-01 00:00:00'
end_datetime: '2017-12-31 23:45:00'

# Variables optimization
scaler_choice_X:
scaler_choice_y:

start_datetime_optimization: '2015-01-01 00:00:00'
end_datetime_optimization: '2016-12-31 23:45:00'

param_kfold:
    n_splits: 5
    shuffle: True
    random_state: 1

param_grid:
  alpha: [0.1, 1, 10]
  l1_ratio: [0.25, 0.5, 0.75, 1]
  fit_intercept: [True]
  normalize: [False, True]
  precompute: [False]
  max_iter: [1000]
  copy_X: [True]
  tol: [0.0001]
  warm_start: [False]
  positive: [False]
  random_state: [null]
  selection: ['cyclic']

#param_grid:
#  alpha: [1]
#  l1_ratio: [0.5]
#  fit_intercept: [True]
#  normalize: [False]
#  precompute: [False]
#  max_iter: [1000]
#  copy_X: [True]
#  tol: [0.0001]
#  warm_start: [False]
#  positive: [False]
#  random_state: [null]
#  selection: ['cyclic']
#
#param_kfold:
#    n_splits: 2
#    shuffle: True
#    random_state: 1

# Variables global
index: 'Datetime'
start_time: '00:00:00'
end_time: '23:45:00'
time_step_second: 900

# Variables model
model_name: 'long-term0-en1'
estimator_choice: 'en'
