features_time_step: []

features_day: ['Day_en', 'Mois','vac_noel_quebec', 'day_off_quebec', '24DEC', '31DEC',
               'renov_beaubien', 'vac_udem1', 'vac_udem2']

features_todummy: ['Day_en', 'Mois']

time_series: ['11', '32', '34', '15', '44', '65', '31', '33', '35', '47', '13',
       '14', '1', '9', '5', '18', '36', '24', '68', '43', '8', '64', '10',
       '55', '3', '49', '51', '2', '19', '56', '7', '6', '4', '48', '66',
       '25', '23', '28', '39', '54', '60', '27', '20', '46', '12', '21',
       '62', '52', '41', '50', '30', '16', '37', '40', '26', '67', '57',
       '61', '42', '45', '38', '29', '58', '63', '22', '59', '53', '17']


start_datetime: '2015-01-01 00:00:00'
end_datetime: '2017-12-31 23:45:00'

# Variables optimization
scaler_choice_X:
scaler_choice_y: 'minmax'

start_datetime_optimization: '2015-01-01 00:00:00'
end_datetime_optimization: '2016-12-31 23:45:00'

param_kfold:
    n_splits: 5
    shuffle: True
    random_state: 1

param_grid:
    estimator__kernel: ['rbf', 'linear']
    estimator__degree: [3.0]
    estimator__gamma: [1, 0.1, 0.01, 0.001]
    estimator__coef0: [0.0]
    estimator__tol: [0.001]
    estimator__C: [0.001, 0.01, 0.1, 1.0, 10]
    estimator__epsilon: [0.1]
    estimator__shrinking: [True]
    estimator__cache_size: [100.0]
    estimator__verbose: [False]
    estimator__max_iter: [-1]


#param_kfold:
#    n_splits: 2
#    shuffle: True
#    random_state: 1
#
#param_grid:
#    estimator__kernel: ['linear']
#    estimator__degree: [3.0]
#    estimator__gamma: ['auto']
#    estimator__coef0: [0.0]
#    estimator__tol: [0.001]
#    estimator__C: [1.0]
#    estimator__epsilon: [0.1]
#    estimator__shrinking: [True]
#    estimator__cache_size: [200.0]
#    estimator__verbose: [False]
#    estimator__max_iter: [-1]

# Variables global
index: 'Datetime'
start_time: '00:00:00'
end_time: '23:45:00'
time_step_second: 900

# Variables model
model_name: 'long-term0-svr2'
estimator_choice: 'svr'


