# Configuration of the model Historical average


# observation_data_path: csv file path with the observation (header: 'Datetime', 'time_series_id1','time_series_id2', ...)
# exogenous_data_path: csv file path with the exogenous data (header: 'Datetime', 'feature_id1','feature_id2', ...)
# features: selected features of exogenous file
# time_series: selected time-series to learn of observation file
# model_name: name of the model (e.g. 'my_new_model')
# path_to_save: path of the directory in which the model will be saved
# start_date: format 'YYYY-MM-dd hh:mm:ss', starting date of the learning dataset
# end_date: format 'YYYY-MM-dd hh:mm:ss', ending date of the learning dataset


observation_data_path: ['/home/toque/data2/montreal/stm/data/valid_metro_15min_2015_2016_2017_sumpass.csv']
exogenous_data_path: ['/home/toque/data2/date/2013-01-01-2019-01-01_new.csv']
features: ['hms_int_15min', 'Day_id', 'Mois_id', 'vac_noel_quebec', 'day_off_quebec', '24DEC', '31DEC',
           'renov_beaubien', 'vac_udem1', 'vac_udem2']
time_series: ['11', '32', '34', '15', '44', '65', '31', '33', '35', '47', '13', '14',
              '1', '9', '5', '18', '36', '24', '68', '43', '8', '64', '10', '55', '3',
              '49', '51', '2', '19', '56', '7', '6', '4', '48', '66', '25', '23', '28',
              '39', '54', '60', '27', '20', '46', '12', '21', '62', '52', '41', '50', '30',
              '16', '37', '40', '26', '67', '57', '61', '42', '45', '38', '29', '58', '63',
              '22', '59', '53', '17']
model_name: 'lt_ha_mtl_v3'
path_to_save: /home/toque/data2/forecast/model/ha/fit/
start_date: '2015-01-01 00:00:00'
end_date: '2016-12-31 23:45:00'
